name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.eoffcn.com/library/influxdb:2.7.4-alpine
    - name: Push the Docker image
      run: docker push harbor.eoffcn.com/library/influxdb:2.7.4-alpine
